### PR TITLE
bump lodash version

### PR DESCRIPTION
**Pull request by oriSomething**

### CODE REVIEW

**Comment by megawac** [comment]
`^3.5.0` is compatible with `^3.9.3`. I don't see any reason to bump for this

**Comment by oriSomething** [comment]
for minification, when you use the newest version in the rest of the code, it will be smaller

**Comment by jamiebuilds** [comment]
The `^` operator rounds up to the highest compatible version. `^3.0.0` will match up to the highest `3.x` version. You gain nothing by bumping the version here.

**Comment by oriSomething** [comment]
thanks @thejameskyle , good to know

**Pull request closed without merging**
